### ISSUE TITLE
Adatum Corporation Team does not exist

### ISSUE THREAD

**Issue by dagenester** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#101]
# Module: 04
#### Step: 15

Description of issue
There is no Adatum Corporation Team listed; therefore, no General Channel.
I noticed there was an anomaly for the All Company public Group in Microsoft 365 admin center, and a team was never created.  Also, that All Company group was not called Adatum Corporation.  So, a couple issues:  no Adatum Corporation M365 group (which could create a team), or Adatum Corporation was supposed to be All Company, and it's broken.

Repro steps:

1.  See attached file.
![image](https://user-images.githubusercontent.com/38948426/135521047-038385e2-6501-40c2-9d6e-32c0aab587e0.png)

**Comment by geschwei** [comment]
This has been addressed with the latest pull request update.
