### ISSUE TITLE
Lab Instructions

### ISSUE THREAD

**Issue by mrep1085** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#103]
**Description of issues:**
There are some issues with some of the lab instructions.

Please could you change the term "Learning Path" to "Module"? In the course materials, Microsoft have reverted to calling them Modules.

Mod 2, Lab 1, Ex 2, Task 2 - In the Microsoft 365 Admin Center, the word Groups in the left-hand navigation pane has been changed to "Teams and groups". Similarly, "Active groups" has been changed to "Active teams and groups". Also, none of the instructions in this task recognize that the groups are not listed on one page now - they are shown under four tabs, Microsoft 365, Distribution list, Mail-enabled security, and Security. Several steps need to be altered.

Mod 4, lab 3, ex 4, In the Teams Admin Center, "Org-wide settings" no longer exists. Various references to it need to be altered. eg Task 4, step 2; Task 7, step 2; Task 8, step 2; Task 9, step 2

Mod 5, Lab 4, ex 1, task 3, step 2
The URL to download IdFix is now wrong. It should be https://microsoft.github.io/idfix Then you have to go to "Step 2: Install IdFix" and click setup.exe.

**Comment by geschwei** [comment]
This has been addressed with the latest pull request update.
