### ISSUE TITLE
LAB_AK_02_Lab1_Ex3_Add_a_Domain.md

### ISSUE THREAD

**Issue by mrep1085** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#105]
**Lab: 01
 Exercise: 03
 Task: 01**

Description of issue:
The task 1 description is missing the second half of the instructions. See screenshots.
![image](https://user-images.githubusercontent.com/92067627/141280272-f560632a-bf69-46ef-908f-2dc4c5b8f8ad.png)
![image](https://user-images.githubusercontent.com/92067627/141280303-1b66571e-8ba2-42ef-be00-6c6a1a7b785c.png)

**Comment by geschwei** [comment]
Please contact your lab hoster with this issue. we do not assign upn's via GitHub instructions.
