### ISSUE TITLE
LAB_AK_04_Lab3_Ex4_Microsoft_Teams.md -- Teams admin UI has changed

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#106]
# Module: 04
## Lab/Demo: 03
Exercise 4
#### Step: 02-12

Description of issue

UI has changed to invalidate this Task, at least as-written:  In addition to 'External access' now being located under 'Users' instead of  'Org-Wide Settings', the new UI presents us with a 'Choose which external domains your users have access to' option.

Preferred allow/block methodology logic will need to be picked by the CO for allow all, allow only, block only, or block all to resolve for this - with the appropriate setp-by-step updated to match the chosen allow/block methodology.

**Comment by geschwei** [comment]
This has been addressed with the latest pull request update.
