### ISSUE TITLE
LAB_AK_04_Lab3_Ex5_Power_Platform_admin_center.md -- Power Platform default environment name is wrong

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#107]
# Module: 04
## Lab/Demo: 03
Exercise 5
#### Step: 05

Description of issue

In the PP Admin Center, the default environment is listed as 'Adatum Corporation (default)', however it is actually 'Contoso (default)'

**Comment by geschwei** [comment]
This has been addressed with the latest pull request update.
