### ISSUE TITLE
LAB_AK_04_Lab3_Ex4_Microsoft_Teams.md -- LON-CL1: Teams not installed by default

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#108]
# Module: 04
#### Step: 02

Description of issue

In this step it indicates to navigate to the **Microsoft Teams** icon, whether on the dekstop or the tool bar - but this app is not installed.  I may have missed something in previous instructions, but it seems to not be present?

I've re-downloaded the current VM set from the DLC (Release date: 23 December 2020) for LON-CL1 to verify - and no Teams is present in the VM.  While I understand it may not have been included intentionally - My own experience with Teams is that after a few releases and time passes it becomes 'stale' and will require to download the latest version fresh, rather then continue to allow you to just start whatever version you had installed - but shouldn't there be a step added to this section to reference the current Teams download URL for latest version + install steps?

**Comment by geschwei** [comment]
This is by design and is installed with the Microsoft app package.
