### ISSUE TITLE
November Tenant switch leads to missing users Debra Berger & Adele Vance

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#115]
Due to the recent (Nov 19) switch of Tenant used by this course, 2 users referenced in the current instructions -- **Debra Berger** & **Adele Vance** are no longer present in Tenant, and therefore cannot be utilized in **Tasks** instructions as they were previous to the Tenant switch.

**Missing User 1: Debra Berger** is seen first and exclusively in _Learning Path 3 - Lab 2 - Exercise 1 - Manage Administration Delegation, Task 3,_ and it may be best to solve for this by simply architecting her out of the instructions altogether. Alternatively, one could perhaps utilize **Patti Fernandez** or other user account which is provisioned in the current Tenant for the password reset steps previously demoed w/Debra, but as Patti F is used later in the Instructions that might have negative impacts.

**Missing User 2: Adele Vance** is seen in _Learning Path 3 - Lab 2 - Exercise 3 - Manage a Microsoft 365 Apps for enterprise installation, Task 2_ and since it appears the only reason we need to use the account is to delete it in order to free up a 365 E5 license.  Since the current Tenant has these licenses to spare, it is likely the easiest solution to also architect Adele out of existence.

**Comment by geschwei** [comment]
This issue has been addressed in latest pull request update.
