### ISSUE TITLE
Holly Spencer should be Holly Dickson

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#125]
# Module: 03
#### Step: 29

The text refers to "Holly Spencer".  But she's actually called "Holly Dickson"

I think this happens elsewhere in the course too.

**Comment by tfrink** [comment]
We have corrected the two instances of Holly Spencer and replaced them with Holly Dickson. Thanks for bringing this to our attention.
