### ISSUE TITLE
mod 4 - Lab 3 - Adatum logo unavailable

### ISSUE THREAD

**Issue by Fouyoufr** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#131]
# Module: 4
#### Step: 3

Description of issue

The adatum logo is currently unavailable and leads to a broken image in the metting invitation preview....

Repro steps:

Try to access the https://adatum.com/media/adatumlogo.png url...

**Comment by tfrink** [comment]
Thank you for your feedback. We'll review the issue and see if this is something that can be fixed.
