### ISSUE TITLE
Path to iDFix is wrong

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#142]
# Module: 5
## Lab/Demo: 4
Exercise 1
#### Step: 02

Description of issue

The URL to install IdFix is wrong - it gives a 404 error.

I'd suggest using:

https://microsoft.github.io/idfix/

 and then modify step 3 to say:

 Choose "Step 2: Install IdFix" on the left hand side of the page and click setup.exe.

**Comment by tfrink** [comment]
Thanks Annette. I'll investigate this and make the necessary changes.
