### ISSUE TITLE
Cannot verify custom domain

### ISSUE THREAD

**Issue by cjpluta** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#145]
# Module: 2
##### Step: 19

Description of issue 
While QA this lab, adding the custom domain fails when trying to verify.
Custom domain provided by lab provider:
![image](https://user-images.githubusercontent.com/27508895/174637339-86cfe9cf-262b-4c3b-a55e-dd602630421a.png)

Error message:
![image](https://user-images.githubusercontent.com/27508895/174637403-10b2330f-5a7f-424b-bcb0-af04097e24d1.png)

Have tried removing/recreating the forward lookup zone on the DC with no luck. Feels like something is broken between where ever the Azure NS is to however it forwards to the internal DNS/DC.

**Comment by tfrink** [comment]
Thank you for your comment. I see that our lab hosting provider who creates the lab VMs has added notation that a successful verification may take up to 48 hours. This was quite a surprise to see. I've done this lab a million times in testing over the past couple of years and never experienced any issues - up to the other day when I was testing this out. I ran into a similar issue. I'll work with the lab hosting provider to see if anything has changed in the VM. Thanks again for bringing this to our attention.
