### ISSUE TITLE
Learning Path 1 - Lab 1 - Excercise 2

### ISSUE THREAD

**Issue by rony-vargas** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#164]
# Learning Path 2
#### Step: 13 (repeating steps from 10-21)

Description of issue:
When creating the IT Admins Security Group, using the repeated steps from 10-21 as stated in the instructions, the new UI doesn't have the Owners & members selection inline, like the M365 Group Does:
New M365 Group>
![image](https://user-images.githubusercontent.com/49657944/197344953-1cb5f16e-cc91-4e32-82b4-52097e69c087.png)

New Security Group>
![image](https://user-images.githubusercontent.com/49657944/197344999-e370392b-b77d-4e99-b42d-26856c2f153d.png)

**Comment by tfrink** [comment]
This situation is already addressed in the instructions. Please see the Note that appears at the end of step 20. It says:

Note: There is no owner, email address, or privacy setting for Security groups. Members must be added to a Security group after creating the group, which you will do in the next few steps.
