### ISSUE TITLE
Exercises out of order - task relies on steps undertaken in later lab

### ISSUE THREAD

**Issue by sarajfMCT** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#168]
# Learning Path: 03
### Exercise 4 Task: 01

Description of issue: This lab appears to be in the wrong place

Learning Path 3 - Lab 2 - Exercise 4 - Manage secure user access Task 1: Deploy Azure AD Pass-Through Authentication assumes you have already installed Azure AD Connect but this comes in Learning Path 5 - Lab 4 - Exercise 2 - Implement Identity Synchronization Task 1: Install Azure AD Connect and Initiate Synchronization

Either the instructions need updating or this task need to be moved into Lab 4!

**Comment by tfrink** [comment]
Thank you Sara for drawing this to our attention. This was an obvious oversite on our part. We are correcting this issue by moving both the content back into Learning Path 5 and the lab into Lab 4. We will wait and make the changes at the end of the week so as not to disrupt existing classes.
