### ISSUE TITLE
Lab 4: Azure AD Connect download instructions need to be updated

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#169]
# Module: 05
#### Step: 00

Description of issue
Learning Path 5, Lab 4, Exercise 2, Task 1
Step 5 onwards:  The wizard to access the download for Azure AD Connect has changed, so these instructions need to be updated.

**Comment by tfrink** [comment]
Thanks for the heads-up. The instructions have been updated.

**Comment by AnnetteGill** [comment]
Many thanks!
