### ISSUE TITLE
Issue in Module 4 - Lab 3 - Exercise 9 

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#17]
# Module: 04
#### Step:05
In the top right-side of the screen, select +New Policy 
(the task is in the Middle bottom now, from this point all steps are off.)

Description of issue
Module 4 - Lab 3 - Exercise 9 - Create a DLP Policy using Power Automate
Task 1 # 6 is Name you Policy not Data Policy Name, Steps are way off from that point.
I Do not know how to complete.

If I walk through the dialog nothing shows up. In the business connector and Non-business connector is in different environment. I am not sure how to complete this exercise.

**Comment by CallanTurner** [comment]
Module 4 - Lab 3 - Exercise 9 - Create a DLP Policy using Power Automate
You have to go to https://admin.powerplatform.microsoft.com (URL in labs doesn't work anymore).
The steps in the lab here are old interface. You will perform the following steps after creating a new DLP Policy.
Steps 5 through 9
 
Name = Flow DLP Policy (whatever) >Next
Select the Non-Business tab
Search for SharePoint. Select it then choose "Move to Business"
Select the Business Tab> You should see SharePoint and Outlook.
Next
Select "All Environments".
Review & Create Policy
 
Back to Step 10
This means their connectors can only talk to other connectors (applications) in the Business Category. The Flow will go to "Suspended" until the other connector for Outlook is added into the Business category.
 
Task 2
Step 2 Return to Power platform Admin
Step 4 basically Search for Outlook. Select it then choose "Move to Business".
Save
Back to step 9

Hope this helps

**Comment by tfrink** [comment]
The lab instructions have been updated as per the current update to the course that is releasing Nov 25th.
