### ISSUE TITLE
Lab 4: Installing IdFix

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#170]
# Module: 05
#### Step: 00

Description of issue

Lab 4, Exercise 1, Task 3

Step 3.  Given the resolution in the virtual machine, the left-hand navigation bar often isn't visible in the browser. 

I think it would be clearer to tell the student to click on the hamburger icon at the top left of the screen and choose "Step 2: Install IdFix" from there.

**Comment by tfrink** [comment]
Annette - we've never had any issues with our lab testing. However, while I'm willing to offer your suggestion as an alternative option in this step, I'm confused by what you mean by the "hamburger" icon. I'm not seeing any such icon in the top left portion of the screen. What exactly are you referring to?

**Comment by tfrink** [comment]
Thanks Annette for the explanation and screen shots. I added the following Note to step 3 that says: 

Note: If your browser resolution isn't sufficient, the left-hand navigation pane may not be visible on your machine. If this situation occurs, select the icon (three horizontal lines) in the top left corner of the screen. This displays the navigation pane, from which you can select Step 2: Install IdFix.

**Comment by AnnetteGill** [comment]
Thank you, that will be very helpful.
