### ISSUE TITLE
Export Table to SharePoint List not working in Lab 3 Exercise 3

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#174]
# Lab/Demo: 03
#### Step: 17

Description of issue

In the **Export Table to SharePoint List** when I enter the address and name, I get the following message when I click Next. If I add the SharePoint site to trusted sources it gives me an error as shown in the last screenshot. Any idea what might be causing the issue?

![image](https://user-images.githubusercontent.com/98971092/219643439-c423f3f3-2316-41d2-be85-5dfb232bdb20.png)

![image](https://user-images.githubusercontent.com/98971092/219643552-beb80331-3c82-4a64-bf0a-87695b86c242.png)

![image](https://user-images.githubusercontent.com/98971092/219643733-a13f58d6-3b09-4d9a-b52e-5adee46b65bf.png)

![image](https://user-images.githubusercontent.com/98971092/219643838-37fd525d-f0db-4a6a-ba99-d34fe0b9ebde.png)

Repro steps:

1. Perform all the steps till step 17.
1. Observe the error.

**Comment by tfrink** [comment]
Sorry for the late response. I'll look into this ASAP. I can say that this is the first time I've seen this issue reported, so my guess is it may have had something to do with your environment. We just did a complete review of the MS-100 labs and we didn't run into this issue. I'll get back to you on what I could find.

**Comment by Kiyani1** [comment]
Thank you for your response, just to let you know this is the first time I'm facing this issue as well. it can be due to an issue with the tenant?

**Comment by tfrink** [comment]
I tested this lab, plus we contract with a vendor to test our labs regularly, and they just finished their testing of MS-101 labs last week. Neither of us were able to replicate this issue. Nor have I heard from any other MCTs regarding this problem. My guess is that it's either a tenant issue, or a VM issue related to the lab environment. For now, I'm going to close this issue, but I'll reopen it if we receive another report. Thank you.
