### ISSUE TITLE
Module 7 - Lab 4 - Exercise 2 - Implement Identity Synchronization

### ISSUE THREAD

**Issue by CallanTurner** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#18]
# Module: 7
#### Step: 36 & 54

Description of issue
Step 36.
If the change to Updating Primary SMTP suffix fails try the following Powershell on Ex1
Launch Exchange Management Shell as Administrator
Set-MailBox -Identity "Scotty Heyward" -PrimarySmtpAddress scotty@company####.onelearndns.com" -EmailAddressPolicyEnabled $false 
Not sure if this is the correct solution

Step 54 
Set-MSOLDirSyncEnabled -EnableDirSync $True
Will not run as the earlier step 6 Set-MSOLDirSyncEnabled -EnableDirSync $False can take up to 72 hours to complete.

This also impacts Module 7 - Lab 4 - Exercise 3 - Implement Password Management as AD Connect fails to make the changes stating "Directory Sync is currently in a pending disable state for this directory. Please wait until….fully disabled before trying again".
Curious to know if anyone has ever got Scotty's account to be fixed.

**Comment by MikeVeschi** [comment]
I went to Azure AD Connect / Synchronization Service on Lon-DC1
and ran in this order

Full Import then Delta Sync on on-prem AD connector
Then
Export on Azure connector

Then Module 7 - Lab 4 - Exercise 2,  Task 7 Step 6 ran without error

**Comment by geschwei** [comment]
The issue stated has been resolved in the next upcoming lab update. that will be published Nov 25th.

**Comment by tfrink** [comment]
Due to a recent update to AD Connect, the forked issue such as the one that we purposely created for Scotty Heyward in this lab is now being automatically fixed by AD connect. Therefore, we had to remove this scenario from the lab exercise.
