### ISSUE TITLE
Module 7 - Lab 4 - Exercise 3 - Implement Password Management

### ISSUE THREAD

**Issue by CallanTurner** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#19]
# Module: 7
#### Step: 00

Description of issue
Cannot Implement Password Management as AD Connect fails to make the changes stating "Directory Sync is currently in a pending disable state for this directory. Please wait until….fully disabled before trying again".
Suspect this is a result of running 
Set-MSOLDirSyncEnabed -EnableDirSync $false in earlier lab and you cannot restart it with $true. It errors "You cannot turn off Active Directory Synchronization".
Ad Connect Service Manager still allows manual syncing but wizard will not proceed and says to retry after it starts.

It eventually ran, but it may not be possible in the course time frame to become available. Tell students to persist after class.

**Comment by geschwei** [comment]
The issue stated has been resolved in the next upcoming lab update. that will be published Nov 25th.
