### ISSUE TITLE
solution needed for Module 1 planning exercise

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#20]
# Module: 00
#### Step: 00

Description of issue
solution needed for Module 1 planning exercise.

According to my trainer ppt slides, there should be a model solution
"
"A copy of the planning document is available in the MCT DLC for this course. The document has suggested solutions for each question. Use these suggested answers to help drive the discussion. You should allot approximately 1 hour for this exercise."

Repro steps:

1.
1.
1.

**Comment by tfrink** [comment]
The solution is available in the MCT Download Center (same place that you downloaded the slides, Trainer Prep Guide, and Change Log).
