### ISSUE TITLE
Module 7 - Lab 4 - Exercise 1 - Prepare for Identity Synchronization 

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#21]
# Module: 7
#### Step: 07

Description of issue
Holly Spencer and Maj Hojski dont appear when you run idfix. The other people do show up. Only Klemen matched the lab

![image](https://user-images.githubusercontent.com/24426530/96670420-d898a480-1391-11eb-8a27-4f52f4282e26.png)

Klemen Sic. Update the UserPrincipalName for Klemen to include an extra "@" character.

Lara Raisic. Update the emailAddress attribute for Lara to lara@adatum.com.

Logan Boyle. Update the emailAddress attribute for Logan to logan@adatum.com.

Holly Spencer. Update the emailAddress attribute for Holly to holly @adatum.com. Note: this includes a blank space between “holly” and “@adatum.com”; the blank space has been purposely inserted.

Maj Hojski. Update the emailAddress attribute for Maj to blank characters (“ “).
Repro steps:

1.
1.
1.

**Comment by TesterTesterson1004** [comment]
I concur - this issue basically breaks Task 3 altogether which really negatively affects the beginning portion of the lab.

Attached is a raw .md with a suggested (and tested) set of instructions that you might consider for inclusion ASAP to improve student experience.
[IdFixMod7Task3.txt](https://github.com/MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services/files/5432004/IdFixMod7Task3.txt)

**Comment by tfrink** [comment]
A recent change to the IfFix tool has resulted in the issues with Holly and Maj's accounts to no longer appear. The lab instructions will be updated as per the current update to the course that is releasing Nov 25th.
