### ISSUE TITLE
Module 4-Lab3_Ex9 - DLP Policy Creation / Update needs modifaction

### ISSUE THREAD

**Issue by jmenne** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#24]
# Module: 04
#### Step: 2-9

###Task: 2
#### Step: 3-8

Steps to create and update a DLP Policy need to be updated because of changes in the portal

**Comment by tfrink** [comment]
The lab instructions have been updated as per the current update to the course that is releasing Nov 25th.
