### ISSUE TITLE
TLS/Powershell issue for Module 02 - Lab 1 - Exercise 1

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#25]
# Module: 02
#### Step: 10

( https://github.com/MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services/blob/master/Instructions/Labs/LAB_AK_02_Lab1_Ex1_Initialize_M365_Tenant.md )

Description of issue
install-module command in step 10 will error unless this cmd is pasted into powershell session before running the install-module:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 

Repro steps:

1.
1.
1.

**Comment by geschwei** [comment]
Hi Testertesterson1004 I have tested this issue you have brought to our attention, however I am not seeing what your describing in the issue. what lab host are you currently running our guides in? please reach out to them for the possible solution.
