### ISSUE TITLE
LAB_AK_04_Lab3_Ex3_Ticketing_System.md - Not in .md format

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#28]
This '.md' file appears to not be in .md format but rather in HTML - could it be changed to use standard .md?

**Comment by TesterTesterson1004** [comment]
Any movement on this issue?  Thanks!

**Comment by tfrink** [comment]
TesterTesterson1004 - Is there a problem with how the text-based version of the html code is presented to students by our lab hosting providers? If so, then we will escalate this issue.

At the moment, the next release of this course is scheduled for April 2021. Unless this is an urgent request, we will include this in our list of items to be reviewed for that update.

**Comment by TesterTesterson1004** [comment]
Correct, the issue occurs when parsing the instructions from GH within hosting provider systems - specifically where hosting provider parsers are expecting standard .md.  While it is often possible to workaround this issue when importing a stray doc like this one that is *not* in .md format, there is that added layer of complexity, time, and potential for error.

It just seems that for a variety of purposes - including this one - adhering to standard of .md within GH instructions documents is 
 highly desirable.
