### ISSUE TITLE
Module 3 - Lab 2 - Exercise 1 - O365 site changes

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#29]
# Module: 03
## Lab/Demo: 02
Exercise 1
#### Step: 22 & 29

Description of issue

- In Task 3/Step 22, the option has changed from 'Let me create a password', and instead instructs should say something to the effect of: 'Uncheck the 'Automatically create a password' box, which then allows you to set your own pwd.

- In Task 3/Step 29, the option has changed from 'Send password in email' to 'Email the sign-in info to me'

**Comment by tfrink** [comment]
Thank you for catching these UI changes! We have corrected the lab instruction to reflect the updated UI.
