### ISSUE TITLE
Module 4 - Lab 3 - Exercise 8 & 9: Some Power Automate site changes

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#30]
# Module: 04
## Lab/Demo: 03

Exercise 08
#### Step: 09

- No longer 'Team Flows', it is now labelled 'Shared with me'

&
Exercise 09
#### Step: 12 & 17

- No longer 'Team Flows', it is now labelled 'Shared with me'

&

Exercise 09
#### Step: 2 & 9

- No longer 'Team Flows', it is now labelled 'Shared with me'

**Comment by tfrink** [comment]
Thank you for catching these UI changes! We have updated the instructions to reflect these changes.
