### ISSUE TITLE
Module 4 - Lab 3 - Exercise 10 - Several minor changes since course release

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#32]
# Module: 04
#### Step: 00

Description of issue
Some changes to sites since docs originally written:

- Task 1, Steps 35 & 41: The option to 'Rename' a filed is now 'Rename for this visual'.

- Task 2, Step 5: The site shows 3 options now: All/Content/Datasets+dataflows

- Task 2, Step 18: The menu is now 'Edit' not Web view and the choice is 'mobile view' not 'phone view'

**Comment by tfrink** [comment]
Thank you for providing us with this list of UI changes! We have incorporated them into the instructions as you indicated.
