### ISSUE TITLE
Module 3 - Lab 2 - Exercise 1 - PowerShell Code

### ISSUE THREAD

**Issue by atsoeiro** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#33]
# Module: 03
#### Step: 09 and 11

Description of issue
In Task 2/Step 09 and 11 the powershell code has a small problem.

The problem is:

![Capture](https://user-images.githubusercontent.com/32068828/105019387-f089ce00-5a3d-11eb-9ddd-52431f9a7322.PNG)

The solution
**$role** = Get-MsolRole -RoleName "Service support administrator"
**$role** = Get-MsolRole -RoleName "Billing administrator"

**Comment by tfrink** [comment]
Sorry about this. This was left over from the previous version of this file that was coded in html, and it appears we missed this when we converted it to markdown. This has been fixed.
