### ISSUE TITLE
Transformed Lab_AK_04_Lab3_Ex3_Ticketing_System from html to markdown

### ISSUE THREAD

**Issue by jmenne** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#39]
I've transformed the Lab File from html format to markdown, so it'll be easier to maintain the file in the future. 

[LAB_AK_04_Lab3_Ex3_Ticketing_System.zip](https://github.com/MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services/files/5910191/LAB_AK_04_Lab3_Ex3_Ticketing_System.zip)

**Comment by geschwei** [comment]
Hi Jmenne,

Please submit this request as a pull request. Thank you.
