### ISSUE TITLE
LAB_AK_03_Lab1_Ex2_Set_up_trial_tenant.md -- invalid URL

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#4]
# Module: 03
#### Step: 1

Description of issue
The shortened URL referenced -- http://aka.ms/t01i -- for whatever reason no longer redirects properly to the 'Microsoft Online Services Sign-In Assistant for IT Professionals RTW' tool.   Newest version I see is https://www.microsoft.com/en-us/download/details.aspx?id=41950 ?

Repro steps:
access http://aka.ms/t01i in browser, get redirected to a generic/top-level MSFT site page of https://www.microsoft.com/en-us/?ref=aka instead of desired tool download page.

**Comment by tfrink** [comment]
Interesting - our review team just validated all URLs about 3 days before release and this was not caught. I made this fix. Thanks for the URL.

**Comment by TesterTesterson1004** [comment]
Thank you!  🙂

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
