### ISSUE TITLE
Tenant not initialized

### ISSUE THREAD

**Issue by sc211166** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#50]
# Module: 02
#### Step: 21

In the **Choose users for targeted release** pane that appears, select inside the **Who should receive targeted releases?** field. This displays the list of active users (these are the ten Microsoft 365 user accounts created for your tenant by your lab hosting provider). In this list, select each of the following users (Note: You have to select each user, one at a time; after selecting a user, you must select inside the field again to re-display the list so that you can display the next user): 

	- **Alex Wilber**
	- **Joni Sherman**
	- **Lynne Robbins**
	- **MOD Administrator** <br/>

    **Note:** Alex, Joni, and Lynne are administrators who are part of Holly's pilot team. Their accounts will be used throughout the labs for this course.

Description of issue
The tenant is not populated with the users, so many tasks cannot be completed 
Repro steps:

1.
1.
1.

**Comment by geschwei** [comment]
I have reviewed this issue. And have tried to reproduce it. however, I have not successfully seen the problem in question. Please work with your learning partner to resolve the issue. thank you.
