### ISSUE TITLE
Error trying to save changes to default policy rule in 'Office 365 Security and Compliance->Threat Management->Policy'

### ISSUE THREAD

**Issue by FireyJoe** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#64]
# Module: 4
## Lab/Demo: 3
##Exercise 1
#### Step: 11

Description of issue

On hitting save after editing Default anti-malware policy, an error is returned: "Client Error: An error occurred when updating the policy. Please try it later.

Repro steps:

We haven't been able to find a combination of edit options which will allow the Default policy to be saved. Additionally, some options described in the instructions, such as "Yes, and use the default notification text", seem to be missing from the interface.

![ms-100 office admin center anti-malware default policy error](https://user-images.githubusercontent.com/47234227/116757704-97d2b580-a9dc-11eb-9570-a04cab980528.JPG)

**Comment by LodsCory** [comment]
I can confirm that this is an issue. I have tried modifying roles but this client error makes this portion of the lab dead in the water. It looks like there may need to be an adjustment to the instructions guiding users to the new compliance portal to modify policies?

**Comment by geschwei** [comment]
Thank you for bringing this to my attention. currently, I'm working on a workaround for this issue.

**Comment by FireyJoe** [comment]
In MicrosoftLearning/MS-500-Microsoft-365-Security#80, it was pointed out that entering "All Users" under "Groups" should work here. We also had success entering the full domain of the tenant under "Domains", but I'm not sure if they are strictly equivalent.

**Comment by geschwei** [comment]
Hi Everyone, I addressed this issue, the problem has to due with a permissions role. I have added the Organization management role for ease of use in order to use the malware policies.

**Comment by kursijaDinesh** [comment]
@geschwei 

I had issue in Module 3 related to Safe Attachments for two users & both worked fine.

Below are the steps & works fine:

1) Connect to Exchange Online:
A) $user = Get-Credential           ( Please M365 Global Admin or Security Admin account)

B) $session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $user -Authentication Basic -AllowRedirection

C) Import-PSSession $session

2) Create a direct Safe Attachment policy in Exchange Online but it will fail as it needs OranizationaCustomization. You can check the error.
New-SafeAttachmentPolicy -Name "Marketing Block Attachments" -Enable $true -Redirect $true -RedirectAddress globaladminuser@domainname.onmicrosoft.com

3) Enable-OrganizationCustomization -confirm            ( Type A to All )

4) Again run the command mentioned in step 2. & policy will get created.

5)  If policy gets created in Exchange, You can try from M365 Console

Thanks,

DK
