### ISSUE TITLE
Module 4 - Lab 3 Exercise 3 Task 2 - The POWERSHELL STILL HAS TYPOS

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#65]
# Module: 00
#### Step: 00

Description of issue
The powershell has a case sensitive typo. and one of the labels is wrong.

fails every time - so simple to fix can someone in the Product Team please actually runt he lab and amend it...

lines 73-79 is the section Title / issue title etc.

Repro steps:

1.
1.
1.

**Comment by geschwei** [comment]
Thanks Ed, ill take a look.

**Comment by geschwei** [comment]
Hi Ed, I have updated the script inside the lab. I'm just waiting for the lab team to publish the change.

**Comment by edbakermct** [comment]
Thanks George hopefully won’t need it unless it’s still in the new version 😀

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
