### ISSUE TITLE
Instructions to download the 'Microsoft Online Services Sign-In Assistant for IT Professionals RTW needs to be removed from the lab.

### ISSUE THREAD

**Issue by Johnny-5-Alive77** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#66]
# Module: 2
#### Step: 1

Description of issue
The download for the Microsoft Online Services Sign-In Assistant is no longer available or needed as of Windows 2008. Please remove from the lab.

**Comment by StevenLODS** [comment]
Bumping this

**Comment by geschwei** [comment]
I have resolved this issue. The Microsoft sign-in assistant has been removed from this module.
