### ISSUE TITLE
All modules: Using a domain controller as administration workstation is a bad practice

### ISSUE THREAD

**Issue by Rokory** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#69]
# Module: all
#### Step: all

A domain controller should not be used as an administrator's workstation. Most tasks in the course can easily performed on CL1.

**Comment by Rokory** [comment]
I will change the labs to be performed on CL1 instead of DC1.

**Comment by geschwei** [comment]
We are going to keep the current option. Thank you for your suggestion.
