### ISSUE TITLE
'Change the Number of lines for editing ' is not available

### ISSUE THREAD

**Issue by velden** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#7]
# Module: 4
#### Step: 25

Description of issue
'Change the Number of lines for editing ' is not available

Repro steps:

Follow steps 21 to 24 and find that this options in step 25 is not available.

**Comment by tfrink** [comment]
The lab instructions will be updated as per the current update to the course that is releasing Nov 25th.
