### ISSUE TITLE
Module 3, lab 2, exercise 2, task 2: GUI glitch

### ISSUE THREAD

**Issue by Rokory** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#73]
# Module: 3
##### Step: 9

Description of issue

There is no **Exchange activity** drop-down. Instead, there is a **Mailbox usage** tab. The same is true for step 11. At the top, in the breadcrum navibgation, go back to **Usage**, scroll down to **SharePoint files** and click **View more**. 

![image](https://user-images.githubusercontent.com/15704399/125207819-edee8f80-e28e-11eb-8252-67555f56f58b.png)

**Comment by geschwei** [comment]
resolved thank you for the bug info.
