### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by rlthompson904** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#8]
# Module: 04
#### Step: 06

Description of issue: Lab Mentions Service Request System.xlsx, BackupFile.xlsx, and ImportCsvToSharepointList.ps1. Files are not available on GitHub or on the LDC.

Repro steps:

1. Look in Documents folder 
1.
1.

**Comment by tfrink** [comment]
My apologies. I have added the 4 files to the Allfiles folder in Github:

https://github.com/MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services/tree/master/Allfiles

There are 4 files - Backupfile.xlsx, ImportCsvtoSharepointList.ps1, and Service Request system.csv and .xlsx.
