### ISSUE TITLE
Lab 3, Exercise 2: Advanced Permissions not available

### ISSUE THREAD

**Issue by Rokory** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#82]
# Module: 4
#### Step: 6 and following

In a group-connected site, the advanced permissions are not available. The task cannot be performed.

**Comment by geschwei** [comment]
I have gone through with the current lab steps and have the advanced permissions settings option.
![image](https://user-images.githubusercontent.com/54861423/125669614-c7db8b71-23b4-45ee-b721-cbef30328e22.png)

**Comment by Rokory** [comment]
In my testing this is not consistently available for all tenants in every case. I could not observe a certain pattern, but in 50 % of the sites, it is not available. However, customizing a group-connected site is not an officially recommended practice. See https://docs.microsoft.com/en-us/sharepoint/customize-sharepoint-site-permissions

> While SharePoint allows considerable customization of site permissions, we highly recommend using the built-in SharePoint groups for communication site permissions and managing team site permissions through the associated Microsoft 365 group.
