### ISSUE TITLE
Module 4, exercise 6, task 4: Swap step 8 and 9

### ISSUE THREAD

**Issue by Rokory** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#85]
# Module: 4
#### Step: 8

Steps 8 and 9 should be swapped. Otherwise, editing the Title1 field is not possible anymore.

**Comment by geschwei** [comment]
I don't believe this is a quality of life issue. I have run through the lab and it doesn't cause any significant issues.

**Comment by Rokory** [comment]
The lab does not work the way it is described. If the steps are swapped, everything is fine.
