### ISSUE TITLE
Module 7, exercise 1, task 4: Task not necessary and should be removed

### ISSUE THREAD

**Issue by Rokory** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#86]
# Module: 7
### Task: 4

This task is not necessary and should be removed completely. This probably remained from earlier versions of the course that used Internet Explorer.

**Comment by geschwei** [comment]
Hi Rokory, 

Thank you for your insight. We will keep task 4  to prevent possible unforeseen issues that might arise.
