### ISSUE TITLE
Powershell Script file for module_05 Lab_04 Exercise_01 not found in the Repo

### ISSUE THREAD

**Issue by sudhakavya** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#97]
# Module: 05
## Lab/Demo: 04
###Exercise: 01
#### Step: 04

Description of issue

CreateProblemUsers.ps1 script file doesn't exists in the Repo Allfiles. 

Refer the Below Link:

https://github.com/MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services/tree/master/Allfiles

@tfrink @geschwei @billwood44

**Comment by geschwei** [comment]
Hi Suhakavya,

Thank you for reaching out.
This script is embedded inside the  VM and is not meant to be inside the Repo.

**Comment by sudhakavya** [comment]
@geschwei  Where can I find that Embedded Script VM template?

**Comment by geschwei** [comment]
@sudhakavya the script is not meant to be augmented And is hidden to the students.
